name: Blog CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Project Files
        run: ls -R

      - name: Validate HTML Exists
        run: test -f index.html

      - name: Finished
        run: echo "Blog validation successful!"
